name: Build zImage

on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt-get install -y bison build-essential curl flex \
          g++-multilib gcc-multilib git-core gnupg gperf \
          lib32ncurses5-dev lib32readline-gplv2-dev lib32z1-dev \
          libesd0-dev libncurses5-dev libsdl1.2-dev \
          libwxgtk2.8-dev libxml2 libxml2-utils lzop \
          openjdk-6-jdk openjdk-6-jre pngcrush schedtool \
          squashfs-tools xsltproc zip zlib1g-dev

      - name: Clone Kernel Source
        run: |
          git clone https://github.com/qliazar/htc_kernel_wildfire.git --depth=1
          cd htc_kernel_wildfire
        

      - name: Get Toolchains
        run: |
          wget https://android.googlesource.com/platform/prebuilt/+archive/6c89c6601a699707500003b782406482c4c3050b/linux-x86/toolchain/arm-eabi-4.4.3.tar.gz
          tar -xvf arm-eabi-4.4.3.tar.gz
          ls -la bin/

      - name: Build kernel
        run: |
          export ARCH=arm
          export CROSS_COMPILE=$(pwd)/bin/arm-eabi-
          make cyanogen_wildfire_defconfig
          make -j$(nproc)

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: built-kernel
          path: <kernel-source-dir>/arch/arm/boot/zImage
